version: '3.8'
services:
  backend:
    build: ./wyer-backend
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - DATABASE_URL=postgres://postgres:Arnold%401@localhost:5432/wyer_db
      - EMAIL_USER=${EMAIL_USER}
      - EMAIL_PASS=${EMAIL_PASS}
    depends_on:
      - db
    networks:
      - app-network

  frontend:
    build: ./wyer-frontend
    ports:
      - "3001:80"
    depends_on:
      - backend
    networks:
      - app-network

  db:
    image: postgres:17
    environment:
      - POSTGRES_DB=wyer_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=Arnold@1
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge